// Self-hosted emoji rendering.
//
// The app used to render emoji as plain Unicode characters and let the
// browser draw them with whatever color-emoji font the OS/browser provides.
// That font isn't under our control: Windows periodically ships a redesign
// (the 2024 "Fluent Emoji" flat style replaced the old glossy Segoe UI
// Emoji), and any given OS's font may simply be a version or two behind
// the newest Unicode emoji (e.g. Windows briefly rendered 🪭, added in
// Unicode 15.0, as a blank tofu box). Since students hit this app from a
// mix of devices, "whatever the OS happens to have" means the same story
// looks different — or broken — for different kids.
//
// To make rendering consistent, we bundle a fixed set of Twemoji SVGs
// (see public/emoji/, generated by scripts/sync-emoji-assets.mjs) and
// render emoji as <img> tags pointing at those local files instead of
// relying on native glyph rendering.
import twemoji from '@twemoji/api'
import { EMOJI_CODEPOINTS } from './emojiManifest'

const AVAILABLE = new Set(EMOJI_CODEPOINTS)

// Resolves an emoji character to its self-hosted SVG URL, or null if it's
// not in our bundled set (falls back to native rendering — see Emoji.tsx).
export function emojiToSrc(emoji: string): string | null {
  let cp = twemoji.convert.toCodePoint(emoji)
  if (!AVAILABLE.has(cp) && cp.endsWith('-fe0f')) {
    const stripped = cp.slice(0, -'-fe0f'.length)
    if (AVAILABLE.has(stripped)) cp = stripped
  }
  return AVAILABLE.has(cp) ? `/emoji/${cp}.svg` : null
}
